<?php

/**
 * The public-facing functionality of the plugin.
 *
 * @link       http://torbara.com
 * @since      1.0.0
 *
 * @package    Ang_Commando_Staff_Team
 * @subpackage Ang_Commando_Staff_Team/public
 */

/**
 * The public-facing functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Ang_Commando_Staff_Team
 * @subpackage Ang_Commando_Staff_Team/public
 * @author     Aleksandr Glovatskyy <alex1278@list.ru>
 */
class Ang_Commando_Staff_Team_Public {

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	public $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	public $version;

        /**
	 * The post type.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $post_type    The post type generated by this plugin.
	 */
        
        public $post_type_name;
        
        /**
	 * Options of admin page
	 *
         *
         * @var type 
         */
        
        private $options;
        
        
	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param      string    $plugin_name       The name of the plugin.
	 * @param      string    $version    The version of this plugin.
	 */
        
	public function __construct( $plugin_name, $version, $post_type_name ) {

		$this->plugin_name       =      $plugin_name;
		$this->version           =      $version;
		$this->post_type_name    =      $post_type_name;

	}
        
        /**
        * Check if option page exists and get options
        *
        * Calls from 'ang-commando-staff-team.php' class 'Ang_Commando_Staff_Team'
        *
        * 
        * 
        * @since     1.0.0
        */
        
        public function get_options() {
            if ( get_option( 'ang_commando_staff_team_options' ) ) :
                $this->options = get_option( 'ang_commando_staff_team_options' );
            endif;
        }

	/**
	 * Register the stylesheets for the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Ang_Commando_Staff_Team_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Ang_Commando_Staff_Team_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'css/ang-commando-staff-team-public.css', array(), $this->version, 'all' );
                wp_enqueue_style( $this->plugin_name. '-font-awesome', plugin_dir_url( __FILE__ ) . 'css/font-awesome.min.css', array(), $this->version, 'all' ); // original font awesome
                
                if($this->options[ 'uikit_css' ] == 'yes'){
                    wp_enqueue_style( $this->plugin_name. '-uikit-final', plugin_dir_url( __FILE__ ) . 'css/uikit-final.css', array(), $this->version, 'all' ); // base warp styles, not all
                }
	}

	/**
	 * Register the JavaScript for the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Ang_Commando_Staff_Team_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Ang_Commando_Staff_Team_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */
		wp_enqueue_script( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'js/ang-commando-staff-team-public.js', array( 'jquery' ), $this->version, false );
                
                if($this->options[ 'uikit_js' ] == 'yes'){
                    wp_enqueue_script( 'uikit', plugin_dir_url( __FILE__ ) . 'js/uikit.js', array( 'jquery' ), $this->version, true ); // uikit base js
                }
	}
        

        /**
        * Register plugin widgets
        *
        * @since   1.0.0
        */
        public function register_widgets() {
    //        register_widget( 'ANG_Timeline_Vertical' );
        }

       /**
        * Register cpt shortcodes
        *
        * @since   1.0.0
        */
        public function register_shortcodes() {
            add_shortcode( $this->post_type_name, array( $this, 'archive_cpt_shortcode') );
        }


        /**
         * Display cpt in list archive shortcode [commando]
         *
         * @since   1.0.0
         * @param   array   $attr     Array of attributes
         * @return  string  generated html by shortcode
         */
        
        public function archive_cpt_shortcode($atts){
            extract(shortcode_atts(array(
                'post_type'     =>  $this->post_type_name,
                'limit'         =>  2,
            ), $atts));

        ob_start();
        $teacher = new WP_Query(array( 'post_type' => $post_type, 'posts_per_page' => $limit));
        if ($teacher->have_posts()) :
                while ( $teacher->have_posts() ) : $teacher->the_post();
        ?>
                        <article id="post-<?php the_ID(); ?>" <?php post_class('uk-article uk-padding-top-remove ang-commando-archive'); ?> data-permalink="<?php the_permalink(); ?>">

                            <div class="uk-grid uk-grid-collapse uk-grid-width-medium-1-2" data-uk-grid-match>
                                <div>
                                    <div class="ang-member-info uk-overflow-hidden uk-block uk-block-large">
                                        <!--team member header-->

                                            <header class="ang-member-header uk-clearfix">
                                                <img src="wp-content/themes/ology/images/svg/uniform.svg" alt="teacher2" width="50" height="50" />
                                                <div>
                                                    <h4 class="uk-panel-title uk-margin-top-remove uk-margin-bottom-remove">
                                                        <?php $team_meta = get_post_meta(get_the_ID()); ?>
                                                            <span><a href="<?php the_permalink() ?>" title="<?php the_title_attribute(); ?>"><?php the_title(); ?></a></span>
                                                    </h4>
                                                    <p class="uk-margin-remove">
                                                       <?php print esc_html($team_meta['_position'][0]);?>
                                                    </p>
                                                </div>
                                            </header>

                                        <!--team member short description-->
                                        <?php
                                            $exp = get_the_excerpt();
                                            print "<div class='ang-member-excerpt'><p>". do_shortcode($exp). "</p></div>";
                                        ?>

                                        <!--team member skills-->
                                        <?php $team_meta = get_post_custom();
                    //                            ang_debug($team_meta);
                                                $skill_meta = array();
                                                for($i = 1; $i<=3; $i++){
                                                    if(isset($team_meta['_skill_name'.$i]) && !empty($team_meta['_skill_name'.$i][0]) ){
                                                        $skill_meta[get_post_meta( get_the_ID(), '_skill_name'.$i, true)] = get_post_meta( get_the_ID(), '_skill_level'.$i, true );
                                                    }
                                                }
                                                //skill piecharts
                                                if(!empty($skill_meta)) {
                                                        print '<div class="ang-member-progress-group">';  
                                                            foreach($skill_meta as $k=>$v){
                                                                if( $v ) {
                                                                    print sprintf( '<div class="ang-member-progress">
                                                                                        <p class="uk-margin-remove uk-clearfix" data-team-progress="%2$s"><span class="uk-float-left">%1$s</span><span class="ang-team-progress-val uk-float-right"></span></p>
                                                                                        <div class="uk-progress uk-progress-mini uk-progress-primary uk-active">
                                                                                            <div class="uk-progress-bar"></div>
                                                                                        </div>
                                                                                    </div>', esc_html($k), esc_html($v)
                                                                                );
                                                                }
                                                            }
                                                        print '</div>';
                                                }
                                        ?>
                                    </div>
                                </div>

                                <?php if (has_post_thumbnail()) :
                                    $thumb_id = get_post_thumbnail_id( get_the_ID() ); //add post thumbnail id;
                                    $img = wp_prepare_attachment_for_js ( $thumb_id ); // get image data array
                                    $image_attributes = wp_get_attachment_image_src( $img["id"], 'full' ); ?>
                                    <div class="ang-post-image-cover" style="background: url(<?php echo esc_url ($image_attributes[0]); ?>) no-repeat center / cover">
                                        <img src="<?php echo $image_attributes[0] ?>"
                                             width="<?php echo $image_attributes[1] ?>"
                                             height="<?php echo $image_attributes[2] ?>"
                                             alt="<?php echo $img["alt"]; ?>"
                                             title="<?php echo $img["title"];?>"
                                             class="uk-visible-small">
                                    </div>
                                <?php endif; ?>
                            </div>

                        </article>
                <?php endwhile; ?>
            <?php endif; ?>
        <?php wp_reset_postdata();
        return ob_get_clean();
    }
    
        /**
        * Check if redirect option is set and redirect
        *
        *
        * Calls from 'ang-commando-staff-team.php' class 'Ang_Commando_Staff_Team'
        *
        * @since     1.0.0
        */
        
        public function ang_plugin_activation_redirect() {
            if ( $this->options[ 'redirect' ] ) :
                $old_val = $this->options;
                $old_val[ 'redirect' ] = false;
                update_option( 'ang_commando_staff_team_options', $old_val );
                wp_safe_redirect( admin_url( 'edit.php?post_type='.$this->post_type_name.'&page=ang_commando_staff_team_settings' ) );
            endif;
        }
        
        
        
    public function ang_plugin_custom_styles() {
        ?>
        <style>
            
            .smartcat_accordion h3.sc_commando_name{
                background-color: #<?php echo $this->options[ 'main_color' ]; ?>
            }
            
            #sc_our_commando .sc_commando .sc_commando_name a{ color: #<?php echo $this->options[ 'main_color' ]; ?>; }
            #sc_our_commando .sc_commando .sc_commando_content, 
            #sc_our_commando.smartcat_slide .sc_commando_read_more a{ color: #<?php echo $this->options[ 'text_color' ]; ?>; }
            #sc_our_commando .sc_commando .sc_commando_name a { font-size: <?php echo $this->options[ 'title_size' ]; ?>px; }
            #sc_our_commando.smartcat_icons .fa,
            #sc_our_commando.smartcat_columns .sc_commando .fa{ color: #<?php echo $this->options[ 'main_color' ]; ?>; border: 2px solid #<?php echo $this->options[ 'main_color' ]; ?> }
            #sc_our_commando.smartcat_icons .sc_commando:hover .fa,
            #sc_our_commando.smartcat_slide .sc_commando_name,
            .sc_our_commando_panel .sc-right-panel .sc-name,
            .sc_our_commando_panel .sc-right-panel .sc-icon,
            .sc_our_commando_panel .sc-right-panel .sc-skills .progress,
            #sc_our_commando_lightbox .progress,
            .smartcat_accordion .ui-accordion-content .progress{ background: #<?php echo $this->options[ 'main_color' ]; ?> }
            #sc_our_commando.smartcat_slide .sc_commando_content{ color: #fff; background: #<?php echo $this->options[ 'text_color' ]; ?> }
            #sc_our_commando.smartcat_icons a{ color: #<?php echo $this->options['main_color']; ?> }
            #sc_our_commando.smartcat_zoomOut .sc_commando .sc_commando_inner .sc_commando_read_more a,
            #sc_our_commando.smartcat_slide .sc_commando_name a{ color: #fff; }
            #sc_our_commando.smartcat_zoomOut .sc_commando .sc_commando_inner .sc_commando_read_more a{ background: #<?php echo $this->options['accent_color']; ?>; }
            #sc_our_commando .sc_commando .sc_commando_read_more a{ color : #<?php echo $this->options['accent_color'] ?> }
            #sc_our_commando.smartcat_zoomOut .sc_commando .sc_commando_inner{ background: #<?php echo $this->options['background_color'] ?>; }
            .sc_personal_quote span.fa-quote-left{ color: #<?php echo $this->options['main_color']; ?>; }
          
        </style>
        <?php
    }

        /**
         * Single content
         */
        
        
        public function ang_set_plugin_single_content( $content ) {

            global $post;

            if ( is_single() ) :
                if ( $post->post_type == $this->post_type_name &&
                        $this->options[ 'single_template' ] == 'standard'

                ) :

                    $facebook = get_post_meta( get_the_ID(), 'commando_facebook', true );
                    $twitter = get_post_meta( get_the_ID(), 'commando_twitter', true );
                    $linkedin = get_post_meta( get_the_ID(), 'commando_linkedin', true );
                    $gplus = get_post_meta( get_the_ID(), 'commando_gplus', true );
                    $email = get_post_meta( get_the_ID(), 'commando_email', true );

                    $content .= '<div class="clear"></div>'
                            . '<div class="smartcat_commando_single_icons">';
                    $content .= $this->ang_get_social_content( $post->ID );
                    $content .= '</div>';
                endif;
            else :

            endif;

            return $content;
        }

        public function set_social( $id ) {

            $facebook = get_post_meta( $id, 'commando_facebook', true );
            $twitter = get_post_meta( $id, 'commando_twitter', true );
            $linkedin = get_post_meta( $id, 'commando_linkedin', true );
            $gplus = get_post_meta( $id, 'commando_gplus', true );
            $email = get_post_meta( $id, 'commando_email', true );
            $phone = get_post_meta( $id, 'commando_phone', true );
            $download = get_post_meta( $id, 'commando_download', true );

            if( $this->options['social_link_style'] == 'round' ) :

                $this->get_social($facebook, $twitter, $linkedin, $gplus, $email, $phone, $download);

            else :

                $this->get_social_icons($facebook, $twitter, $linkedin, $gplus, $email, $phone, $download);

            endif;

        }

        public function get_social( $facebook, $twitter, $linkedin, $gplus, $email, $phone, $download ) {
            if ( $facebook != '' )
                echo '<a href="' . $facebook . '">'.esc_html__('Facebook', 'ang-commando-staff-team').'</a>';
            if ( $twitter != '' )
                echo '<a href="' . $twitter . '">'.esc_html__('Twitter', 'ang-commando-staff-team').'</a>';
            if ( $linkedin != '' )
                echo '<a href="' . $linkedin . '">'.esc_html__('Linkedin', 'ang-commando-staff-team').'</a>';
            if ( $gplus != '' )
                echo '<a href="' . $gplus . '">'.esc_html__('Google+', 'ang-commando-staff-team').'</a>';
            if ( $email != '' )
                echo '<a href=mailto:"' . $email . '">'.esc_html__('E-mail', 'ang-commando-staff-team').'</a>';
            if ( $download != '' )
                echo '<a href="' . $download . '" target="_BLANK">'.esc_html__('Download', 'ang-commando-staff-team').'</a>';
            if ( $phone != '' )
                echo '<a href="tel:' . $phone . '">'.esc_html__('Phone', 'ang-commando-staff-team').'</a>';
        }

        public function get_social_icons( $facebook, $twitter, $linkedin, $gplus, $email, $phone, $download ) {

            if ( $facebook != '' )
                echo '<a ' . $this->add_target() . ' href="' . $facebook . '"><span class="fa fa-facebook"></span></a>';
            if ( $gplus != '' )
                echo '<a ' . $this->add_target() . ' href="' . $gplus . '"><span class="fa fa-google-plus"></span></a>';
            if ( $twitter != '' )
                echo '<a ' . $this->add_target() . ' href="' . $twitter . '"><span class="fa fa-twitter"></span></a>';
            if ( $email != '' )
                echo '<a href=mailto:' . $email . '><span class="fa fa-envelope-o"></span></a>';
            if ( $linkedin != '' )
                echo '<a ' . $this->add_target() . ' href="' . $linkedin . '"><span class="fa fa-linkedin"></span></a>';


            if ( $phone != '' )
                echo '<a href=tel:' . $phone . '><span class="fa fa-phone"></span></a>';  
            if ( $download != '' )
                echo '<a ' . $this->add_target() . ' href="' . $gplus . '" target="_BLANK"><span class="fa fa-download"></span></a>';

        }

        public function ang_get_social_content( $id ) {

            $content = null;

            $facebook = get_post_meta( $id, 'commando_facebook', true );
            $twitter = get_post_meta( $id, 'commando_twitter', true );
            $linkedin = get_post_meta( $id, 'commando_linkedin', true );
            $gplus = get_post_meta( $id, 'commando_gplus', true );
            $email = get_post_meta( $id, 'commando_email', true );
            $phone = get_post_meta( $id, 'commando_phone', true );
            $download = get_post_meta( $id, 'commando_download', true );


            if ( $facebook != '' )
                $content .= '<a href="' . $facebook . '">'.esc_html__('Facebook', 'ang-commando-staff-team').'</a>';
            if ( $twitter != '' )
                $content .= '<a href="' . $twitter . '">'.esc_html__('Twitter', 'ang-commando-staff-team').'</a>';
            if ( $linkedin != '' )
                $content .= '<a href="' . $linkedin . '">'.esc_html__('Linkedin', 'ang-commando-staff-team').'</a>';
            if ( $gplus != '' )
                $content .= '<a href="' . $gplus . '">'.esc_html__('Google+', 'ang-commando-staff-team').'</a>';
            if ( $email != '' )
                $content .= '<a href=mailto:"' . $email . '">'.esc_html__('E-mail', 'ang-commando-staff-team').'</a>';
            if ( $download != '' )
                $content .= '<a href="' . $download . '" target="_BLANK">'.esc_html__('Download', 'ang-commando-staff-team').'</a>';
            if ( $phone != '' )
                $content .= '<a href="tel:' . $phone . '">'.esc_html__('Phone', 'ang-commando-staff-team').'</a>';

            return $content;
        }
    
}
