<?php

/**
 * The file that defines the core plugin class
 *
 * A class definition that includes attributes and functions used across both the
 * public-facing side of the site and the admin area.
 *
 * @link       http://torbara.com
 * @since      1.0.0
 *
 * @package    Ang_Commando_Staff_Team
 * @subpackage Ang_Commando_Staff_Team/includes
 */

/**
 * The core plugin class.
 *
 * This is used to define internationalization, admin-specific hooks, and
 * public-facing site hooks.
 *
 * Also maintains the unique identifier of this plugin as well as the current
 * version of the plugin.
 *
 * @since      1.0.0
 * @package    Ang_Commando_Staff_Team
 * @subpackage Ang_Commando_Staff_Team/includes
 * @author     Aleksandr Glovatskyy <alex1278@list.ru>
 */
class Ang_Commando_Staff_Team {

	/**
	 * The loader that's responsible for maintaining and registering all hooks that power
	 * the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      Ang_Commando_Staff_Team_Loader    $loader    Maintains and registers all hooks for the plugin.
	 */
	protected $loader;

	/**
	 * The unique identifier of this plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $plugin_name    The string used to uniquely identify this plugin.
	 */
	protected $plugin_name;

	/**
	 * The current version of the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $version    The current version of the plugin.
	 */
	protected $version;
        
	/**
	 * Define the core functionality of the plugin.
	 *
	 * Set the plugin name and the plugin version that can be used throughout the plugin.
	 * Load the dependencies, define the locale, and set the hooks for the admin area and
	 * the public-facing side of the site.
	 *
         * @since    1.0.0
	 * @access   protected
	 * @var      bool    $devmode    Define the core functionality for development.
	 */
	protected $devmode;

        /**
	 * The custom post type generated by the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $post_type_name    The custom post type.
	 */
        protected $post_type_name;
        
        /**
	 * The custom taxonomy name (slug) generated by the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $tax_name    The custom taxonomy.
	 */
        protected $tax_name;
        
        /**
	 * The second custom taxonomy name (slug) generated by the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $tax_name_second    The second custom taxonomy.
	 */
        protected $tax_name_second;
        
	public function __construct($version = '1.0.0', $plugin_name = 'ang-commando-staff-team', $post_type_name = 'commando', $tax_name = 'commando_cat', $tax_name_second = 'department', $devmode = TRUE) {
                
                $this->post_type_name       =    defined( 'ANG_CO_POST_TYPE_NAME' ) ? ANG_CO_POST_TYPE_NAME : $post_type_name;
                $this->tax_name             =    defined( 'ANG_CO_TAX_NAME' ) ? ANG_CO_TAX_NAME : $tax_name;
                $this->tax_name_second      =    defined( 'ANG_CO_TAX_NAME_SECOND' ) ? ANG_CO_TAX_NAME_SECOND : $tax_name_second;
                
                $this->version              =    $version;
		$this->plugin_name          =    $plugin_name;
		$this->devmode              =    $devmode;

		$this->load_dependencies();
		$this->set_locale();
		$this->define_admin_hooks();
		$this->define_options();
		$this->define_public_hooks();

	}

	/**
	 * Load the required dependencies for this plugin.
	 *
	 * Include the following files that make up the plugin:
	 *
	 * - Ang_Commando_Staff_Team_Loader. Orchestrates the hooks of the plugin.
	 * - Ang_Commando_Staff_Team_i18n. Defines internationalization functionality.
	 * - Ang_Commando_Staff_Team_Admin. Defines all hooks for the admin area.
	 * - Ang_Commando_Staff_Team_Public. Defines all hooks for the public side of the site.
	 *
	 * Create an instance of the loader which will be used to register the hooks
	 * with WordPress.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function load_dependencies() {

		/**
		 * The class responsible for orchestrating the actions and filters of the
		 * core plugin.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'includes/class-ang-commando-staff-team-loader.php';

		/**
		 * The class responsible for defining internationalization functionality
		 * of the plugin.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'includes/class-ang-commando-staff-team-i18n.php';

		/**
		 * The class responsible for defining all actions that occur in the admin area.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-ang-commando-staff-team-admin.php';
                
        /**
         * The class responsible for custom post type
         */
        require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-ang-commando-staff-team-post-type.php';
        
        /**
         * The class responsible for plugin option page
         */
        require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-ang-commando-staff-team-option-page.php';
        
        /**
         * The class responsible for widgets of this plugin, not for now
         */
        //foreach ( glob( plugin_dir_path( dirname( __FILE__ ) ). 'public/widgets/*.php' ) as $widget ){ require_once $widget; } //include widget files
        
		/**
		 * The class responsible for defining all actions that occur in the public-facing
		 * side of the site.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'public/class-ang-commando-staff-team-public.php';

		$this->loader = new Ang_Commando_Staff_Team_Loader();

	}

	/**
	 * Define the locale for this plugin for internationalization.
	 *
	 * Uses the Ang_Commando_Staff_Team_i18n class in order to set the domain and to register the hook
	 * with WordPress.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function set_locale() {

		$plugin_i18n = new Ang_Commando_Staff_Team_i18n();
                $plugin_i18n->set_domain( $this->get_plugin_name() ); //ang
            
		$this->loader->add_action( 'plugins_loaded', $plugin_i18n, 'load_plugin_textdomain' );

	}

	/**
	 * Register all of the hooks related to the admin area functionality
	 * of the plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function define_admin_hooks() {

		$plugin_admin = new Ang_Commando_Staff_Team_Admin( $this->get_plugin_name(), $this->get_version(), $this->get_devmode());

		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );
                
        // Custom post type
        $new_post_type = new Ang_Commando_Staff_Team_Post_Type($this->get_post_type_name(), $this->get_tax_name(), $this->get_tax_name_second(), $this->get_plugin_name());

        $this->loader->add_action( 'init', $new_post_type, 'register_custom_post_type' );
        $this->loader->add_action( 'init', $new_post_type, 'register_first_custom_taxonomy' );
        $this->loader->add_action( 'init', $new_post_type, 'register_second_custom_taxonomy' );
        $this->loader->add_filter( 'template_include', $new_post_type, 'include_template_single_cpt' ); // locate single post template
        $this->loader->add_filter( 'template_include', $new_post_type, 'include_template_archive_cpt' ); // locate archive post template
        
        /*
         * add theme support post thumbnails in admin listing
         */
        if ( is_admin() ) {
            global $pagenow;
            if ( $pagenow == 'edit.php' && isset( $_GET['post_type'] ) && esc_attr( $_GET['post_type'] ) == $new_post_type->post_type_name ) {
                $this->loader->add_filter( 'manage_edit-' . $new_post_type->post_type_name . '_columns', $new_post_type, 'register_custom_column_headings' );
                $this->loader->add_action( 'manage_' . $new_post_type->post_type_name . '_posts_custom_column', $new_post_type, 'register_custom_column' );
            }
        }
        $this->loader->add_action( 'admin_menu', $new_post_type, 'add_custom_meta_box' );
        $this->loader->add_action( 'save_post', $new_post_type, 'save_custom_meta_box' );
        
	}
        
        /**
         * 
         */
        
        private function define_options(){
            $plugin_options = new Ang_Commando_Staff_Team_Option_Page($this->get_plugin_name(), $this->get_post_type_name());
            //$plugin_options->get_options();
               
               $this->loader->add_action( 'admin_menu', $plugin_options, 'ang_plugin_options_menu' );
               
        }
	/**
	 * Register all of the hooks related to the public-facing functionality
	 * of the plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function define_public_hooks() {

		$plugin_public = new Ang_Commando_Staff_Team_Public( $this->get_plugin_name(), $this->get_version(), $this->get_post_type_name() );

		$this->loader->add_action( 'wp_enqueue_scripts', $plugin_public, 'enqueue_styles' );
		$this->loader->add_action( 'wp_enqueue_scripts', $plugin_public, 'enqueue_scripts' );
                
                // hooks with options
                
                $this->loader->add_action( 'init', $plugin_public, 'get_options' );

                $this->loader->add_action( 'wp_head', $plugin_public, 'ang_plugin_custom_styles' );
                $this->loader->add_filter( 'the_content', $plugin_public, 'ang_set_plugin_single_content' );
                $this->loader->add_action( 'admin_init', $plugin_public, 'ang_plugin_activation_redirect' );
                // register shrtcode
                $this->loader->add_action( 'init', $plugin_public, 'register_shortcodes' );
                // register widget
                $this->loader->add_action('widgets_init', $plugin_public, 'register_widgets' );
                
        // not needed for now, will enable in future versio

                // $this->loader->add_filter( 'ang_timeline_events', $plugin_public, 'ang_timeline_event_terms' );

        // not needed for now
        // ang
        //         if ( class_exists('Vc_Manager') ) {
        //             $this->loader->add_action( 'vc_before_init', $plugin_public, 'integrate_shortcode_with_vc' );
        //         }
        
	}
        
	/**
	 * Run the loader to execute all of the hooks with WordPress.
	 *
	 * @since    1.0.0
	 */
	public function run() {
		$this->loader->run();
	}

	/**
	 * The name of the plugin used to uniquely identify it within the context of
	 * WordPress and to define internationalization functionality.
	 *
	 * @since     1.0.0
	 * @return    string    The name of the plugin.
	 */
	public function get_plugin_name() {
		return $this->plugin_name;
	}

	/**
	 * The reference to the class that orchestrates the hooks with the plugin.
	 *
	 * @since     1.0.0
	 * @return    Ang_Commando_Staff_Team_Loader    Orchestrates the hooks of the plugin.
	 */
	public function get_loader() {
		return $this->loader;
	}

	/**
	 * Retrieve the version number of the plugin.
	 *
	 * @since     1.0.0
	 * @return    string    The version number of the plugin.
	 */
	public function get_version() {
		return $this->version;
	}
        
	/**
	 * Dev mode for options page.
	 *
	 * @since     1.0.0
	 * @return    bool    Define the core functionality of the plugin for development.
	 */
	public function get_devmode() {
		return $this->devmode;
	}
	
	/**
	 * The custom post type generated by the plugin.
	 *
	 * @since     1.0.0
	 * @return    string    The custom post type.
	 */
	public function get_post_type_name() {
		return $this->post_type_name;
	}
	/**
	 * The custom taxonomy name (slug) generated by the plugin.
	 *
	 * @since     1.0.0
	 * @return    string    The custom taxonomy.
	 */
	public function get_tax_name() {
		return $this->tax_name;
	}
       
	/**
	 * The second custom taxonomy name (slug) generated by the plugin.
	 *
	 * @since     1.0.0
	 * @return    string    The second custom taxonomy.
	 */
	public function get_tax_name_second() {
		return $this->tax_name_second;
	}
}
